[variables]
NODE_VERSION = "20.18.0"

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start:prod" 